import type { Metadata } from "next";
import "./globals.css";

// 移除Next.js字体导入

// 然后可以在globals.css中添加传统的@font-face定义

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
